image: barichello/godot-ci:3.1.1

stages:
  - tests

before_script:
  - mkdir -v -p build/windows

unitTests:
  stage: tests
  script:
    - godot -s addons/gut/gut_cmdln.gd -d --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_