image: barichello/godot-ci:4.2.1

stages:
  - import-assets
  - build
  - tests

before_script:
  - mkdir -v -p build/windows

import-assets:
  stage: import-assets
  script:
    - godot --headless --v --editor --quit

unitTests:
  stage: tests
  script:
    - godot --editor --quit-after 1000
    - godot --headless --v -d -s res://addons/gut/gut_cmdln.gd -gconfig

windows:
  stage: build
  script:
    - cd build/windows
    - godot --headless --v --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe