image: barichello/godot-ci:4.2.1

stages:
  - import-assets
  - build
  - tests

before_script:
  - mkdir -v -p build/windows

import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --editor --quit

unitTests:
  stage: tests
  script:
    - godot --headless -d -s --path $PWD res://addons/gut/gut_cmdln.gd -ginclude_subdirs -gdir=res://Tests -gprefix=test_ -gexit

windows:
  stage: build
  script:
    - cd build/windows
    - godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe