image: barichello/godot-ci:4.2.1

stages:
  - build
  - tests

before_script:
  - mkdir -v -p build/windows

unitTests:
  stage: tests
  script:
    - godot -s addons/gut/gut_cmdln.gd -d --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_

windows:
  stage: build
  script:
    - godot -v --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/$EXPORT_NAME.exe